In [17]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine
import warnings

# warnings.filterwarnings('ignore')

In [18]:
postgres_user = 'dsbc_student'
postgres_pw = '7*.8G9QH21'
postgres_host = '142.93.121.174'
postgres_port = '5432'
postgres_db = 'useducation'

engine = create_engine('postgresql://{}:{}@{}:{}/{}'.format(postgres_user, postgres_pw, 
                                                            postgres_host, postgres_port, postgres_db))

data = pd.read_sql_query('select * from useducation', con=engine)

engine.dispose()

In [27]:
# question1
data.info()
data.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1492 entries, 0 to 1491
Data columns (total 25 columns):
PRIMARY_KEY                     1492 non-null object
STATE                           1492 non-null object
YEAR                            1492 non-null int64
ENROLL                          1229 non-null float64
TOTAL_REVENUE                   1280 non-null float64
FEDERAL_REVENUE                 1280 non-null float64
STATE_REVENUE                   1280 non-null float64
LOCAL_REVENUE                   1280 non-null float64
TOTAL_EXPENDITURE               1280 non-null float64
INSTRUCTION_EXPENDITURE         1280 non-null float64
SUPPORT_SERVICES_EXPENDITURE    1280 non-null float64
OTHER_EXPENDITURE               1229 non-null float64
CAPITAL_OUTLAY_EXPENDITURE      1280 non-null float64
GRADES_PK_G                     1319 non-null float64
GRADES_KG_G                     1360 non-null float64
GRADES_4_G                      1361 non-null float64
GRADES_8_G                      1361 non-null float64
GRADES_12_G                     1361 non-null float64
GRADES_1_8_G                    1361 non-null float64
GRADES_9_12_G                   1361 non-null float64
GRADES_ALL_G                    1319 non-null float64
AVG_MATH_4_SCORE                536 non-null float64
AVG_MATH_8_SCORE                532 non-null float64
AVG_READING_4_SCORE             533 non-null float64
AVG_READING_8_SCORE             498 non-null float64
dtypes: float64(22), int64(1), object(2)
memory usage: 291.5+ KB

,PRIMARY_KEY,STATE,YEAR,ENROLL,TOTAL_REVENUE,FEDERAL_REVENUE,STATE_REVENUE,LOCAL_REVENUE,TOTAL_EXPENDITURE,INSTRUCTION_EXPENDITURE,...,GRADES_4_G,GRADES_8_G,GRADES_12_G,GRADES_1_8_G,GRADES_9_12_G,GRADES_ALL_G,AVG_MATH_4_SCORE,AVG_MATH_8_SCORE,AVG_READING_4_SCORE,AVG_READING_8_SCORE
0,1992_ALABAMA,ALABAMA,1992,NaN,2678885.0,304177.0,1659028.0,715680.0,2653798.0,1481703.0,...,57948.0,58025.0,41167.0,471564.0,196386.0,676174.0,208.327876,252.187522,207.963517,NaN
1,1992_ALASKA,ALASKA,1992,NaN,1049591.0,106780.0,720711.0,222100.0,972488.0,498362.0,...,9748.0,8789.0,6714.0,79117.0,30847.0,112335.0,NaN,NaN,NaN,258.859712
2,1992_ARIZONA,ARIZONA,1992,NaN,3258079.0,297888.0,1369815.0,1590376.0,3401580.0,1435908.0,...,55433.0,49081.0,37410.0,437127.0,175210.0,614881.0,215.253932,265.366278,206.212716,262.169895
3,1992_ARKANSAS,ARKANSAS,1992,NaN,1711959.0,178571.0,958785.0,574603.0,1743022.0,964323.0,...,34632.0,36011.0,27651.0,281338.0,123113.0,405259.0,210.206028,256.312090,208.634458,264.619665
4,1992_CALIFORNIA,CALIFORNIA,1992,NaN,26260025.0,2072470.0,16546514.0,7641041.0,27138832.0,14358922.0,...,418418.0,363296.0,270675.0,3286034.0,1372011.0,4717112.0,208.398961,260.892247,196.764414,NaN

In [60]:
# question1
data.isnull().sum()*100/len(data)

PRIMARY_KEY                      0.000000
STATE                            0.000000
YEAR                             0.000000
ENROLL                          17.627346
TOTAL_REVENUE                   14.209115
FEDERAL_REVENUE                 14.209115
STATE_REVENUE                   14.209115
LOCAL_REVENUE                   14.209115
TOTAL_EXPENDITURE               14.209115
INSTRUCTION_EXPENDITURE         14.209115
SUPPORT_SERVICES_EXPENDITURE    14.209115
OTHER_EXPENDITURE               17.627346
CAPITAL_OUTLAY_EXPENDITURE      14.209115
GRADES_PK_G                     11.595174
GRADES_KG_G                      8.847185
GRADES_4_G                       8.780161
GRADES_8_G                       8.780161
GRADES_12_G                      8.780161
GRADES_1_8_G                     8.780161
GRADES_9_12_G                    8.780161
GRADES_ALL_G                    11.595174
AVG_MATH_4_SCORE                64.075067
AVG_MATH_8_SCORE                64.343164
AVG_READING_4_SCORE             64.276139
AVG_READING_8_SCORE             66.621984
dtype: float64

In [99]:
# question2
data1 = data.copy()
c = data1.columns.drop(['PRIMARY_KEY', 'STATE', 'YEAR'])
# print(c)
for column in c:
    data1[column] = data1[column].fillna(data1[column].mean())
# data1.info()

In [97]:
# question3
data2 = data.copy()
c = data2.columns.drop(['PRIMARY_KEY', 'STATE', 'YEAR'])
for column in c:
    for i in range(0, len(data2)):
        if pd.isnull(data2[column][i]):
            data2[column] = data2[column].fillna(data2[data2['YEAR'] == data2['YEAR'][i]][column].mean())
# data2
# it is different from the sample solution, why?????

In [98]:
# question3_sample_solution
fill_list = ["ENROLL", "TOTAL_REVENUE", "FEDERAL_REVENUE", 
             "STATE_REVENUE", "LOCAL_REVENUE", "TOTAL_EXPENDITURE", 
             "INSTRUCTION_EXPENDITURE", "SUPPORT_SERVICES_EXPENDITURE",
             "OTHER_EXPENDITURE", "CAPITAL_OUTLAY_EXPENDITURE", "GRADES_PK_G", 
             "GRADES_KG_G", "GRADES_4_G", "GRADES_8_G", "GRADES_12_G", "GRADES_1_8_G", 
             "GRADES_9_12_G", "GRADES_ALL_G"]

education3_df = data.copy()

years = education3_df["YEAR"].unique()
for col in fill_list:
    for year in years:
        education3_df.loc[education3_df["YEAR"] == year, col] = education3_df.loc[education3_df["YEAR"] == year, col].fillna(
            education3_df[education3_df["YEAR"] == year][col].mean())
# education3_df

In [110]:
data3 = data.copy()
c = data3.columns.drop(['PRIMARY_KEY', 'STATE', 'YEAR'])
for column in c:
    data3[column] = data3[column].interpolate()
#     data3[column] = data3[column].extrapolate()
# data3  
# how to do extrapolation?????

In [115]:
for column in c:
    print(pd.concat([data[column], data1[column], data2[column], data3[column]], axis=1).describe())
    
# why data1 and data2 give the same number?????

             ENROLL        ENROLL        ENROLL        ENROLL
count  1.229000e+03  1.492000e+03  1.492000e+03  1.456000e+03
mean   9.159308e+05  9.159308e+05  9.159952e+05  1.005984e+06
std    1.065280e+06  9.667725e+05  9.667726e+05  1.009158e+06
min    4.386600e+04  4.386600e+04  4.386600e+04  4.386600e+04
25%    2.583140e+05  3.150940e+05  3.150940e+05  2.973995e+05
50%    6.483130e+05  8.204140e+05  8.204140e+05  7.540845e+05
75%    1.014528e+06  9.211780e+05  9.211780e+05  1.595024e+06
max    6.307022e+06  6.307022e+06  6.307022e+06  6.307022e+06
       TOTAL_REVENUE  TOTAL_REVENUE  TOTAL_REVENUE  TOTAL_REVENUE
count   1.280000e+03   1.492000e+03   1.492000e+03   1.492000e+03
mean    9.092082e+06   9.092082e+06   8.938035e+06   1.111164e+07
std     1.174519e+07   1.087818e+07   1.088477e+07   1.200155e+07
min     4.656500e+05   4.656500e+05   4.656500e+05   4.656500e+05
25%     2.186305e+06   2.546261e+06   2.546261e+06   2.546261e+06
50%     5.079546e+06   6.359310e+06   6.359310e+06   6.351760e+06
75%     1.085985e+07   9.276958e+06   9.276958e+06   1.803650e+07
max     8.921726e+07   8.921726e+07   8.921726e+07   8.921726e+07
       FEDERAL_REVENUE  FEDERAL_REVENUE  FEDERAL_REVENUE  FEDERAL_REVENUE
count     1.280000e+03     1.492000e+03     1.492000e+03     1.492000e+03
mean      7.663723e+05     7.663723e+05     7.372304e+05     8.922691e+05
std       1.145242e+06     1.060702e+06     1.063118e+06     1.106788e+06
min       3.102000e+04     3.102000e+04     3.102000e+04     3.102000e+04
25%       1.893540e+05     2.170200e+05     2.170200e+05     2.170200e+05
50%       4.033765e+05     5.167410e+05     5.167410e+05     5.165190e+05
75%       8.289660e+05     7.663723e+05     7.505032e+05     1.411794e+06
max       9.990221e+06     9.990221e+06     9.990221e+06     9.990221e+06
       STATE_REVENUE  STATE_REVENUE  STATE_REVENUE  STATE_REVENUE
count   1.280000e+03   1.492000e+03   1.492000e+03   1.492000e+03
mean    4.216553e+06   4.216553e+06   4.176961e+06   4.913351e+06
std     5.543072e+06   5.133895e+06   5.134817e+06   5.423675e+06
min     0.000000e+00   0.000000e+00   0.000000e+00   0.000000e+00
25%     1.153097e+06   1.356434e+06   1.356434e+06   1.356434e+06
50%     2.537074e+06   3.127639e+06   3.127639e+06   3.119414e+06
75%     5.080939e+06   4.269811e+06   4.269811e+06   8.020633e+06
max     5.090457e+07   5.090457e+07   5.090457e+07   5.090457e+07
       LOCAL_REVENUE  LOCAL_REVENUE  LOCAL_REVENUE  LOCAL_REVENUE
count   1.280000e+03   1.492000e+03   1.492000e+03   1.492000e+03
mean    4.109157e+06   4.109157e+06   4.023844e+06   5.306024e+06
std     5.482971e+06   5.078230e+06   5.082558e+06   5.900909e+06
min     2.209300e+04   2.209300e+04   2.209300e+04   2.209300e+04
25%     7.158345e+05   9.447962e+05   9.447962e+05   9.447962e+05
50%     2.055780e+06   2.697257e+06   2.697257e+06   2.650904e+06
75%     4.768680e+06   4.109157e+06   3.959033e+06   8.584803e+06
max     3.610526e+07   3.610526e+07   3.610526e+07   3.610526e+07
       TOTAL_EXPENDITURE  TOTAL_EXPENDITURE  TOTAL_EXPENDITURE  \
count       1.280000e+03       1.492000e+03       1.492000e+03
mean        9.196681e+06       9.196681e+06       9.051760e+06
std         1.197813e+07       1.109393e+07       1.109965e+07
min         4.816650e+05       4.816650e+05       4.816650e+05
25%         2.165404e+06       2.523968e+06       2.523968e+06
50%         5.234506e+06       6.520224e+06       6.520224e+06
75%         1.074519e+07       9.434922e+06       9.434922e+06
max         8.532013e+07       8.532013e+07       8.532013e+07

       TOTAL_EXPENDITURE
count       1.492000e+03
mean        1.114374e+07
std         1.212433e+07
min         4.816650e+05
25%         2.523968e+06
50%         6.499891e+06
75%         1.801704e+07
max         8.532013e+07
       INSTRUCTION_EXPENDITURE  INSTRUCTION_EXPENDITURE  \
count             1.280000e+03             1.492000e+03
mean              4.762966e+06             4.762966e+06
std               6.293004e+06             5.828468e+06
min               2.655490e+05             2.655490e+05
25%               1.168032e+06             1.343611e+06
50%               2.657452e+06             3.358142e+06
75%               5.568028e+06             4.938820e+06
max               4.396452e+07             4.396452e+07

       INSTRUCTION_EXPENDITURE  INSTRUCTION_EXPENDITURE
count             1.492000e+03             1.492000e+03
mean              4.678848e+06             5.792260e+06
std               5.832135e+06             6.376549e+06
min               2.655490e+05             2.655490e+05
25%               1.343611e+06             1.343611e+06
50%               3.358142e+06             3.318778e+06
75%               4.938820e+06             9.130766e+06
max               4.396452e+07             4.396452e+07
       SUPPORT_SERVICES_EXPENDITURE  SUPPORT_SERVICES_EXPENDITURE  \
count                  1.280000e+03                  1.492000e+03
mean                   2.680331e+06                  2.680331e+06
std                    3.353349e+06                  3.105812e+06
min                    1.399630e+05                  1.399630e+05
25%                    6.357900e+05                  7.673688e+05
50%                    1.525406e+06                  1.913844e+06
75%                    3.229651e+06                  2.795888e+06
max                    2.605802e+07                  2.605802e+07

       SUPPORT_SERVICES_EXPENDITURE  SUPPORT_SERVICES_EXPENDITURE
count                  1.492000e+03                  1.492000e+03
mean                   2.628778e+06                  3.324275e+06
std                    3.108396e+06                  3.500830e+06
min                    1.399630e+05                  1.399630e+05
25%                    7.673688e+05                  7.673688e+05
50%                    1.913844e+06                  1.910412e+06
75%                    2.795888e+06                  5.435244e+06
max                    2.605802e+07                  2.605802e+07
       OTHER_EXPENDITURE  OTHER_EXPENDITURE  OTHER_EXPENDITURE  \
count       1.229000e+03       1.492000e+03       1.492000e+03
mean        4.292046e+05       4.292046e+05       4.199160e+05
std         5.340693e+05       4.846832e+05       4.850992e+05
min         1.154100e+04       1.154100e+04       1.154100e+04
25%         1.028310e+05       1.354282e+05       1.354282e+05
50%         2.715960e+05       3.672335e+05       3.672335e+05
75%         5.186000e+05       4.568915e+05       4.568915e+05
max         3.995951e+06       3.995951e+06       3.995951e+06

       OTHER_EXPENDITURE
count       1.456000e+03
mean        5.004288e+05
std         5.253843e+05
min         1.154100e+04
25%         1.279618e+05
50%         3.415810e+05
75%         8.490842e+05
max         3.995951e+06
       CAPITAL_OUTLAY_EXPENDITURE  CAPITAL_OUTLAY_EXPENDITURE  \
count                1.280000e+03                1.492000e+03
mean                 9.027693e+05                9.027693e+05
std                  1.327562e+06                1.229564e+06
min                  1.270800e+04                1.270800e+04
25%                  1.815645e+05                2.163398e+05
50%                  5.102595e+05                6.482175e+05
75%                  9.668515e+05                9.027693e+05
max                  1.022366e+07                1.022366e+07

       CAPITAL_OUTLAY_EXPENDITURE  CAPITAL_OUTLAY_EXPENDITURE
count                1.492000e+03                1.492000e+03
mean                 9.108093e+05                1.033524e+06
std                  1.229723e+06                1.272901e+06
min                  1.270800e+04                1.270800e+04
25%                  2.163398e+05                2.163398e+05
50%                  6.482175e+05                6.436235e+05
75%                  9.593529e+05                1.717212e+06
max                  1.022366e+07                1.022366e+07
         GRADES_PK_G    GRADES_PK_G    GRADES_PK_G    GRADES_PK_G
count    1319.000000    1492.000000    1492.000000    1492.000000
mean    17601.614102   17601.614102   17368.662103   15926.059316
std     30016.166447   28221.111094   28228.445454   28669.479212
min         0.000000       0.000000       0.000000       0.000000
25%      2021.000000    2449.000000    2449.000000    1544.000000
50%      8106.000000   10505.000000   10505.000000    5910.500000
75%     22295.000000   19149.250000   19149.250000   19561.000000
max    250911.000000  250911.000000  250911.000000  250911.000000
         GRADES_KG_G    GRADES_KG_G    GRADES_KG_G    GRADES_KG_G
count    1360.000000    1492.000000    1492.000000    1492.000000
mean    63746.761029   63746.761029   63353.323449   59021.465818
std     80205.138143   76572.547833   76582.968012   78271.025323
min       544.000000     544.000000     544.000000     544.000000
25%     11745.000000   14016.000000   14016.000000    9926.750000
50%     41597.500000   48897.000000   48897.000000   38507.000000
75%     73865.250000   70372.750000   70372.750000   70748.750000
max    530531.000000  530531.000000  530531.000000  530531.000000
          GRADES_4_G     GRADES_4_G     GRADES_4_G     GRADES_4_G
count    1361.000000    1492.000000    1492.000000    1492.000000
mean    64538.927259   64538.927259   64564.773054   59797.646113
std     80293.387625   76684.998585   76685.043867   78406.899202
min       633.000000     633.000000     633.000000     633.000000
25%     13739.000000   15195.500000   15195.500000   10117.250000
50%     43272.000000   49884.500000   49884.500000   38280.500000
75%     75481.000000   71814.250000   71814.250000   72310.250000
max    493415.000000  493415.000000  493415.000000  493415.000000
          GRADES_8_G     GRADES_8_G     GRADES_8_G     GRADES_8_G
count    1361.000000    1492.000000    1492.000000    1492.000000
mean    64271.057311   64271.057311   64193.997284   59511.380027
std     78910.545776   75364.301721   75364.711302   77123.573668
min       437.000000     437.000000     437.000000     437.000000
25%     13342.000000   15682.750000   15682.750000   10252.000000
50%     43339.000000   49571.000000   49571.000000   38114.500000
75%     76566.000000   72131.000000   72131.000000   72598.250000
max    500143.000000  500143.000000  500143.000000  500143.000000
        GRADES_12_G    GRADES_12_G    GRADES_12_G    GRADES_12_G
count    1361.00000    1492.000000    1492.000000    1492.000000
mean    54268.92432   54268.924320   53899.773643   50207.239276
std     67889.27623   64838.328605   64849.252738   66309.867155
min       311.00000     311.000000     311.000000     311.000000
25%     10919.00000   13437.000000   13437.000000    8951.000000
50%     36735.00000   39566.000000   39566.000000   33279.000000
75%     67460.00000   64616.250000   64616.250000   64920.500000
max    498403.00000  498403.000000  498403.000000  498403.000000
       GRADES_1_8_G  GRADES_1_8_G  GRADES_1_8_G  GRADES_1_8_G
count  1.361000e+03  1.492000e+03  1.492000e+03  1.492000e+03
mean   5.192140e+05  5.192140e+05  5.189037e+05  4.810102e+05
std    6.436384e+05  6.147133e+05  6.147141e+05  6.286622e+05
min    4.878000e+03  4.878000e+03  4.878000e+03  4.878000e+03
25%    1.106260e+05  1.211522e+05  1.211522e+05  8.127325e+04
50%    3.457750e+05  4.015865e+05  4.015865e+05  3.097340e+05
75%    6.119050e+05  5.749118e+05  5.749118e+05  5.783400e+05
max    3.929869e+06  3.929869e+06  3.929869e+06  3.929869e+06

       GRADES_9_12_G  GRADES_9_12_G  GRADES_9_12_G  GRADES_9_12_G
count   1.361000e+03   1.492000e+03   1.492000e+03   1.492000e+03
mean    2.470714e+05   2.470714e+05   2.462408e+05   2.286678e+05
std     3.077056e+05   2.938773e+05   2.938895e+05   3.005815e+05
min     1.808000e+03   1.808000e+03   1.808000e+03   1.808000e+03
25%     5.147100e+04   5.919750e+04   5.919750e+04   3.950675e+04
50%     1.642600e+05   1.817010e+05   1.817010e+05   1.472355e+05
75%     2.905020e+05   2.825390e+05   2.825390e+05   2.843505e+05
max     2.013687e+06   2.013687e+06   2.013687e+06   2.013687e+06
       GRADES_ALL_G  GRADES_ALL_G  GRADES_ALL_G  GRADES_ALL_G
count  1.319000e+03  1.492000e+03  1.492000e+03  1.492000e+03
mean   8.024415e+05  8.024415e+05  8.014122e+05  7.478782e+05
std    9.707031e+05  9.126522e+05  9.126566e+05  9.291585e+05
min    7.254000e+03  7.254000e+03  7.254000e+03  7.254000e+03
25%    1.810650e+05  2.293578e+05  2.293578e+05  1.718665e+05
50%    5.503420e+05  6.473260e+05  6.473260e+05  4.591248e+05
75%    9.282755e+05  8.724220e+05  8.724220e+05  8.860948e+05
max    5.944746e+06  5.944746e+06  5.944746e+06  5.944746e+06
       AVG_MATH_4_SCORE  AVG_MATH_4_SCORE  AVG_MATH_4_SCORE  AVG_MATH_4_SCORE
count        536.000000       1492.000000       1492.000000       1492.000000
mean         234.768293        234.768293        224.286780        232.723472
std           10.221511          6.122843          9.956247          9.405215
min          187.134670        187.134670        187.134670        187.134670
25%          229.694352        234.768293        218.410116        226.267129
50%          237.238552        234.768293        218.410116        234.226904
75%          241.995486        234.768293        231.291396        240.163315
max          253.420961        253.420961        253.420961        253.420961
       AVG_MATH_8_SCORE  AVG_MATH_8_SCORE  AVG_MATH_8_SCORE  AVG_MATH_8_SCORE
count        532.000000       1492.000000       1492.000000       1492.000000
mean         278.414711        278.414711        270.658534        275.734024
std           10.159722          6.063038          8.373799          8.754805
min          232.831510        232.831510        232.831510        232.831510
25%          272.761598        278.414711        266.360319        270.096001
50%          280.618803        278.414711        266.360319        275.711254
75%          285.347428        278.414711        274.677587        282.702092
max          300.568235        300.568235        300.568235        300.568235
       AVG_READING_4_SCORE  AVG_READING_4_SCORE  AVG_READING_4_SCORE  \
count           533.000000          1492.000000          1492.000000
mean            218.866154           218.866154           214.910666
std               7.769616             4.641053             5.499181
min             178.557612           178.557612           178.557612
25%             214.663401           218.866154           212.712256
50%             220.416034           218.866154           212.712256
75%             223.999337           218.866154           216.212825
max             236.773867           236.773867           236.773867

       AVG_READING_4_SCORE
count          1492.000000
mean            218.971553
std               5.959927
min             178.557612
25%             216.126818
50%             219.771325
75%             222.684611
max             236.773867
       AVG_READING_8_SCORE  AVG_READING_8_SCORE  AVG_READING_8_SCORE  \
count           498.000000          1492.000000          1492.000000
mean            263.661132           263.661132           263.425247
std               6.803725             3.928132             3.931682
min             236.379102           236.379102           236.379102
25%             259.533171           263.661132           263.307067
50%             265.010912           263.661132           263.307067
75%             268.190121           263.661132           263.307067
max             280.499130           280.499130           280.499130

       AVG_READING_8_SCORE
count          1491.000000
mean            263.267799
std               4.978792
min             236.379102
25%             260.490023
50%             262.617766
75%             266.849675
max             280.499130